use crate::{Access, Authority, DiscoveryKind, HotPathPolicy, ServerSurface, SurfaceDescriptor};

const OBSERVE_READ: Access = Access::OBSERVE.union(Access::READ);
const OBSERVE_READ_CALL: Access = OBSERVE_READ.union(Access::CALL);
const OBSERVE_READ_MUTATE: Access = OBSERVE_READ.union(Access::MUTATE);
const OBSERVE_BLOCK: Access = Access::OBSERVE.union(Access::BLOCK);
const OBSERVE_READ_BLOCK_MUTATE: Access = OBSERVE_READ.union(Access::BLOCK).union(Access::MUTATE);

pub const DEFAULT_SURFACES: &[SurfaceDescriptor] = &[
    SurfaceDescriptor {
        surface: ServerSurface::DedicatedServerExecutable,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::TraceOnly, DiscoveryKind::Signature],
        default_access: Access::OBSERVE,
        hot_path: HotPathPolicy::NotHot,
        public_api: "BuildInfo, ModuleInfo",
        notes: "Identify executable/module hashes and build facts; never replace the executable.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::Source2Networking,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::EngineInterface, DiscoveryKind::Hook],
        default_access: Access::OBSERVE,
        hot_path: HotPathPolicy::InterestGated,
        public_api: "NetMessages, ClientNetworkState",
        notes: "Observe/filter at known hook boundaries; transport/session ownership remains in engine.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::SteamAuth,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::TraceOnly],
        default_access: Access::OBSERVE,
        hot_path: HotPathPolicy::NotHot,
        public_api: "ClientAuthView",
        notes: "Expose status/identity facts only; do not spoof or replace Steam authentication.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::SnapshotGeneration,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::TraceOnly, DiscoveryKind::Signature],
        default_access: Access::OBSERVE,
        hot_path: HotPathPolicy::InterestGated,
        public_api: "SnapshotTrace",
        notes: "Useful for diagnostics and future visibility filters; do not replace serializer/snapshot writer.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::EntitySimulation,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::Hook, DiscoveryKind::Schema],
        default_access: OBSERVE_READ,
        hot_path: HotPathPolicy::Mounted,
        public_api: "Entity, EntityLifecycle, SchemaAccessor",
        notes: "Expose entity handles and curated schema fields with lifetime checks.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::Physics,
        authority: Authority::Engine,
        discovery: &[
            DiscoveryKind::EngineInterface,
            DiscoveryKind::VTableIndex,
            DiscoveryKind::Signature,
        ],
        default_access: OBSERVE_READ_CALL,
        hot_path: HotPathPolicy::Mounted,
        public_api: "TraceSystem, PhysicsView",
        notes: "Safe calls like trace rays are public; direct physics mutation requires a separate capability.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::Prediction,
        authority: Authority::Engine,
        discovery: &[
            DiscoveryKind::Hook,
            DiscoveryKind::VersionedOffset,
            DiscoveryKind::VTableIndex,
        ],
        default_access: Access::OBSERVE,
        hot_path: HotPathPolicy::InterestGated,
        public_api: "PredictionTrace, UsercmdStatus",
        notes: "Expose prediction/usercmd status facts first; mutation is research-only until trace-verified.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::GameRules,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::Schema, DiscoveryKind::Signature],
        default_access: OBSERVE_READ_MUTATE,
        hot_path: HotPathPolicy::NotHot,
        public_api: "GameRules",
        notes: "Curated game-rule fields can be read/mutated after schema validation.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::MapLoading,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::Hook, DiscoveryKind::EngineInterface],
        default_access: OBSERVE_READ_CALL,
        hot_path: HotPathPolicy::NotHot,
        public_api: "MapLifecycle, MapCommands",
        notes: "Expose lifecycle and controlled change/map calls; engine owns actual loading.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::ResourcesAndStringTables,
        authority: Authority::Engine,
        discovery: &[
            DiscoveryKind::EngineInterface,
            DiscoveryKind::Hook,
            DiscoveryKind::Signature,
        ],
        default_access: OBSERVE_READ_CALL,
        hot_path: HotPathPolicy::NotHot,
        public_api: "ResourcePrecache, StringTableView",
        notes: "Expose precache/addon/search-path controls and read-only table diagnostics.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::ProtobufSerializers,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::EngineInterface, DiscoveryKind::Protobuf],
        default_access: OBSERVE_READ,
        hot_path: HotPathPolicy::InterestGated,
        public_api: "ProtoMessageView, ProtoMutationContext",
        notes: "Use engine protobuf serializers only after exact mounted interest.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::ControllerPawn,
        authority: Authority::Engine,
        discovery: &[
            DiscoveryKind::Schema,
            DiscoveryKind::VersionedOffset,
            DiscoveryKind::VTableIndex,
        ],
        default_access: OBSERVE_READ_MUTATE,
        hot_path: HotPathPolicy::Mounted,
        public_api: "PlayerController, PlayerPawn",
        notes: "Primary high-level facade for player state; raw offsets stay internal/versioned.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::UsercmdPipeline,
        authority: Authority::Engine,
        discovery: &[
            DiscoveryKind::Hook,
            DiscoveryKind::Protobuf,
            DiscoveryKind::VersionedOffset,
        ],
        default_access: OBSERVE_READ_BLOCK_MUTATE,
        hot_path: HotPathPolicy::InterestGated,
        public_api: "UsercmdBatch, FastUsercmd, UsercmdMutationContext",
        notes: "Count-only default; compact read/full protobuf/mutation are explicit mounts.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::NetMessagePipeline,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::Hook, DiscoveryKind::Protobuf],
        default_access: OBSERVE_READ_BLOCK_MUTATE,
        hot_path: HotPathPolicy::InterestGated,
        public_api: "NetMessages, FastNetMessage, NetMutationContext",
        notes: "Message id and nested user-message gates before serialization/parsing.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::GameEvents,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::Hook],
        default_access: OBSERVE_BLOCK,
        hot_path: HotPathPolicy::Mounted,
        public_api: "GameEventBus",
        notes: "Named event subscriptions only; payload wrappers must respect engine lifetime.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::EntitySchema,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::Schema],
        default_access: OBSERVE_READ_MUTATE,
        hot_path: HotPathPolicy::Mounted,
        public_api: "SchemaField, EntityProperty",
        notes: "Curated schema fields with generated/versioned accessors.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::EntityIo,
        authority: Authority::Engine,
        discovery: &[DiscoveryKind::Hook, DiscoveryKind::VTableIndex],
        default_access: OBSERVE_BLOCK,
        hot_path: HotPathPolicy::Mounted,
        public_api: "EntityInput, EntityOutput, TouchEvent",
        notes: "Can storm; default logging off and subscriptions class/event filtered.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::ConsoleCommands,
        authority: Authority::Runtime,
        discovery: &[DiscoveryKind::RuntimeOwned, DiscoveryKind::EngineInterface],
        default_access: Access::CALL,
        hot_path: HotPathPolicy::NotHot,
        public_api: "Commands",
        notes: "Runtime-owned command registry backed by engine concommands.",
    },
    SurfaceDescriptor {
        surface: ServerSurface::ChatCommands,
        authority: Authority::Runtime,
        discovery: &[DiscoveryKind::RuntimeOwned, DiscoveryKind::Protobuf],
        default_access: Access::CALL.union(Access::BLOCK),
        hot_path: HotPathPolicy::InterestGated,
        public_api: "ChatCommands",
        notes: "Mount chat protobuf only when chat handlers/commands exist.",
    },
];
